/**
 * Code generation entry point.
 *
 * Multi-language architecture: dispatches to language-specific emitters.
 * Currently supports TypeScript; Go/Python/Swift can be added by
 * creating new emitter modules and adding cases here.
 */

import type {
  TrafficalConfig,
  ConfigEvent,
  ConfigPropertyField,
  ConfigPropertyGroup,
  EventPropertySchema,
} from "../types.ts";
import { compilePropertySchema } from "../config.ts";
import { toPascalCase, generateInterface, schemaFieldToTS } from "./typescript.ts";
import type { CodegenLanguage, CodegenResult } from "./types.ts";

export { toPascalCase } from "./typescript.ts";
export type { CodegenLanguage, CodegenOptions, CodegenResult } from "./types.ts";

export interface GenerateEventTypesOptions {
  language: CodegenLanguage;
  configPath: string;
}

/**
 * Resolve event properties locally by merging property group refs.
 * Works offline using only the local config file.
 */
export function resolveEventSchemaLocally(
  event: ConfigEvent,
  groups: Record<string, ConfigPropertyGroup>
): Record<string, ConfigPropertyField> {
  const merged: Record<string, ConfigPropertyField> = {};

  for (const groupName of event.propertyGroups ?? []) {
    const group = groups[groupName];
    if (group) {
      Object.assign(merged, group.properties);
    }
  }

  // Event-specific properties override group properties
  Object.assign(merged, event.properties ?? {});

  return merged;
}

/**
 * Generate the full type definitions file content for a given config.
 */
export function generateEventTypesContent(
  config: TrafficalConfig,
  options: { language: CodegenLanguage; configPath: string }
): CodegenResult {
  if (options.language !== "typescript") {
    throw new Error(`Language "${options.language}" is not yet supported. Supported: typescript`);
  }

  return generateTypeScript(config, options.configPath);
}

function generateTypeScript(
  config: TrafficalConfig,
  configPath: string
): CodegenResult {
  const paramKeys = Object.keys(config.parameters);
  const eventEntries = Object.entries(config.events || {});
  const groups = config.propertyGroups || {};

  let content = `/**
 * Auto-generated Traffical types
 *
 * Generated from: ${configPath}
 * Do not edit this file manually.
 */

`;

  // Parameter key union type
  if (paramKeys.length > 0) {
    content += `/**\n * All parameter keys defined in traffical.yaml\n */\n`;
    content += `export type TrafficalParameterKey =\n`;
    content += paramKeys.map((key) => `  | "${key}"`).join("\n") + ";\n\n";

    content += `/**\n * Parameter types by key\n */\n`;
    content += `export interface TrafficalParameterTypes {\n`;
    for (const key of paramKeys) {
      const param = config.parameters[key]!;
      let tsType: string;
      switch (param.type) {
        case "string": tsType = "string"; break;
        case "number": tsType = "number"; break;
        case "boolean": tsType = "boolean"; break;
        case "json": tsType = "Record<string, unknown>"; break;
        default: tsType = "unknown";
      }
      content += `  "${key}": ${tsType};\n`;
    }
    content += `}\n\n`;
  } else {
    content += `export type TrafficalParameterKey = never;\n\n`;
    content += `export interface TrafficalParameterTypes {}\n\n`;
  }

  // Event name union type
  if (eventEntries.length > 0) {
    content += `/**\n * All event names defined in traffical.yaml\n */\n`;
    content += `export type TrafficalEventName =\n`;
    content += eventEntries.map(([name]) => `  | "${name}"`).join("\n") + ";\n\n";

    content += `/**\n * Event value types by name\n */\n`;
    content += `export interface TrafficalEventTypes {\n`;
    for (const [name, event] of eventEntries) {
      let tsType: string;
      switch (event.valueType) {
        case "currency":
        case "count":
        case "rate":
          tsType = "number"; break;
        case "boolean":
          tsType = "boolean"; break;
        default:
          tsType = "unknown";
      }
      content += `  "${name}": ${tsType};\n`;
    }
    content += `}\n\n`;

    // Per-event property interfaces
    const interfaceNames: Record<string, string> = {};

    for (const [name, event] of eventEntries) {
      const resolvedProps = resolveEventSchemaLocally(event, groups);
      if (Object.keys(resolvedProps).length === 0) continue;

      const compiled = compilePropertySchema(resolvedProps);
      const interfaceName = `${toPascalCase(name)}Properties`;
      interfaceNames[name] = interfaceName;

      content += `/**\n * Properties for "${name}" event\n */\n`;
      content += generateInterface(interfaceName, compiled, { includeDescriptions: true });
      content += "\n\n";
    }

    // Event properties map
    content += `/**\n * Event properties map — maps event names to their property types\n */\n`;
    content += `export interface TrafficalEventProperties {\n`;
    for (const [name] of eventEntries) {
      const iface = interfaceNames[name];
      if (iface) {
        content += `  "${name}": ${iface};\n`;
      } else {
        content += `  "${name}": Record<string, unknown>;\n`;
      }
    }
    content += `}\n\n`;
  } else {
    content += `export type TrafficalEventName = never;\n\n`;
    content += `export interface TrafficalEventTypes {}\n\n`;
    content += `export interface TrafficalEventProperties {}\n\n`;
  }

  // Helper types
  content += `/**\n * Helper type for type-safe parameter access\n */\n`;
  content += `export type GetParamType<K extends TrafficalParameterKey> = TrafficalParameterTypes[K];\n\n`;
  content += `/**\n * Helper type for type-safe event tracking\n */\n`;
  content += `export type GetEventValueType<N extends TrafficalEventName> = TrafficalEventTypes[N];\n\n`;
  content += `/**\n * Type-safe track function signature\n */\n`;
  content += `export type TypedTrack = <E extends TrafficalEventName>(\n`;
  content += `  event: E,\n`;
  content += `  properties: TrafficalEventProperties[E],\n`;
  content += `  options?: { decisionId?: string; unitKey?: string }\n`;
  content += `) => void;\n`;

  return {
    content,
    extension: ".ts",
    language: "typescript",
  };
}
